# -*- coding: utf-8 -*-
"""CNN–BiLSTM–Attention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEGh5zaR4uGCVcegC8bXx2q9BvzK0Rcg
"""

# ==========================================
# 1. IMPORTS
# ==========================================
import pandas as pd
import numpy as np
import warnings
from scipy.io.arff import loadarff
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, matthews_corrcoef, roc_auc_score
from sklearn.utils import class_weight

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Dense, Conv1D, MaxPooling1D, GlobalAveragePooling1D,
    LSTM, Bidirectional, Concatenate, Dropout,
    MultiHeadAttention, LayerNormalization, Add
)
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow.keras.backend as K

warnings.filterwarnings("ignore")
tf.get_logger().setLevel("ERROR")


# ==========================================
# 2. DATA LOADING (FIXED)
# ==========================================
def load_and_clean_data(filepath):

    data, meta = loadarff(filepath)
    df = pd.DataFrame(data)

    # Decode byte columns
    for col in df.columns:
        if df[col].dtype == object:
            try:
                df[col] = df[col].str.decode("utf-8")
            except:
                pass

    # Convert label column
    label_col = "isDefective"

    df[label_col] = df[label_col].astype(str).str.upper()

    df[label_col] = df[label_col].map({
        "TRUE": 1,
        "FALSE": 0,
        "1": 1,
        "0": 0
    })

    df = df.rename(columns={label_col: "class"})

    return df


# ==========================================
# 3. LOAD DATASETS
# ==========================================
file_names = [
    "Apache.arff",
    "Safe.arff",
    "Zxing.arff"
]

datasets = {}

print("Loading datasets...\n")

for f in file_names:
    name = f.replace(".arff", "")
    datasets[name] = load_and_clean_data(f)
    print(f"Loaded {f}")

dataset_names = list(datasets.keys())


# ==========================================
# 4. FOCAL LOSS
# ==========================================
def focal_loss(gamma=2., alpha=0.25):

    def loss(y_true, y_pred):

        epsilon = 1e-7
        y_pred = K.clip(y_pred, epsilon, 1 - epsilon)

        pt = tf.where(K.equal(y_true, 1), y_pred, 1 - y_pred)

        return -K.mean(alpha * K.pow(1 - pt, gamma) * K.log(pt))

    return loss


# ==========================================
# 5. ADVANCED HYBRID MODEL
# ==========================================
def build_advanced_hybrid(input_shape):

    inputs = Input(shape=input_shape)

    cnn1 = Conv1D(64, 3, padding="same", activation="relu")(inputs)
    cnn2 = Conv1D(64, 5, padding="same", activation="relu")(inputs)
    cnn3 = Conv1D(64, 7, padding="same", activation="relu")(inputs)

    cnn = Concatenate()([cnn1, cnn2, cnn3])

    cnn = MaxPooling1D(2)(cnn)
    cnn = Dropout(0.3)(cnn)

    res = Conv1D(192, 1, padding="same")(inputs)
    res = MaxPooling1D(2)(res)

    cnn = Add()([cnn, res])

    lstm = Bidirectional(LSTM(64, return_sequences=True))(cnn)
    lstm = Dropout(0.3)(lstm)

    attention = MultiHeadAttention(num_heads=4, key_dim=32)(lstm, lstm)

    attention = Add()([attention, lstm])
    attention = LayerNormalization(epsilon=1e-6)(attention)

    x = GlobalAveragePooling1D()(attention)

    x = Dense(128, activation="relu")(x)
    x = Dropout(0.4)(x)

    outputs = Dense(1, activation="sigmoid")(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
        loss=focal_loss(),
        metrics=["accuracy"]
    )

    return model


# ==========================================
# 6. CROSS PROJECT DEFECT PREDICTION
# ==========================================
results = []

early_stopper = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

print("\nStarting Cross-Project Defect Prediction...\n")

for test_name in dataset_names:

    print("=" * 60)
    print(f"Testing on Target Project: {test_name}")
    print("=" * 60)

    train_names = [n for n in dataset_names if n != test_name]

    df_train = pd.concat([datasets[n] for n in train_names], ignore_index=True)
    df_test = datasets[test_name]

    X_train = df_train.drop("class", axis=1).values
    y_train = df_train["class"].values

    X_test = df_test.drop("class", axis=1).values
    y_test = df_test["class"].values

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    input_shape = (X_train.shape[1], 1)

    X_train = X_train.reshape((X_train.shape[0], input_shape[0], 1))
    X_test = X_test.reshape((X_test.shape[0], input_shape[0], 1))

    weights = class_weight.compute_class_weight(
        "balanced",
        classes=np.unique(y_train),
        y=y_train
    )

    cw_dict = {0: weights[0], 1: weights[1]}

    model = build_advanced_hybrid(input_shape)

    model.fit(
        X_train,
        y_train,
        epochs=25,
        batch_size=64,
        validation_split=0.1,
        class_weight=cw_dict,
        callbacks=[early_stopper],
        verbose=0
    )

    y_pred_prob = model.predict(X_test, verbose=0).ravel()

    best_f1 = 0
    best_threshold = 0.5

    for t in np.arange(0.1, 0.9, 0.01):

        preds = (y_pred_prob > t).astype(int)

        score = f1_score(y_test, preds, zero_division=0)

        if score > best_f1:
            best_f1 = score
            best_threshold = t

    print(f"Best threshold: {best_threshold:.2f}")

    y_pred = (y_pred_prob > best_threshold).astype(int)

    fm = f1_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)

    try:
        auc = roc_auc_score(y_test, y_pred_prob)
    except:
        auc = 0.5

    print(f"F1-score: {fm:.4f}")
    print(f"MCC     : {mcc:.4f}")
    print(f"AUC     : {auc:.4f}\n")

    results.append([test_name, fm, mcc, auc])


# ==========================================
# 7. FINAL RESULTS
# ==========================================
results_df = pd.DataFrame(
    results,
    columns=["Test_Project", "F1", "MCC", "AUC"]
)

print("\n" + "=" * 80)
print("FINAL CPDP RESULTS")
print("=" * 80)

print(results_df)

results_df.to_csv("advanced_cpdp_results.csv", index=False)

print("\n✅ Results saved as advanced_cpdp_results.csv")

# ==========================================
# 1. IMPORTS
# ==========================================
import pandas as pd
import numpy as np
import warnings
from scipy.io.arff import loadarff
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, matthews_corrcoef, roc_auc_score
from sklearn.utils import class_weight
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Dense, Conv1D, MaxPooling1D, GlobalAveragePooling1D,
    LSTM, Bidirectional, Concatenate, Dropout,
    MultiHeadAttention, LayerNormalization, Add
)
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow.keras.backend as K

warnings.filterwarnings('ignore')
tf.get_logger().setLevel('ERROR')


# ==========================================
# 2. DATA LOADING
# ==========================================
def load_and_clean_data(filepath):
    data, meta = loadarff(filepath)
    df = pd.DataFrame(data)
    df['class'] = df['class'].str.decode('utf-8')
    df['class'] = (df['class'] == 'buggy').astype(int)
    return df

file_names = ['LC.arff', 'ML.arff', 'PDE.arff', 'EQ.arff', 'JDT.arff']
datasets = {}

print("Loading datasets...\n")
for f in file_names:
    datasets[f.replace('.arff', '')] = load_and_clean_data(f)
    print(f"Loaded {f}")

dataset_names = list(datasets.keys())


# ==========================================
# 3. FOCAL LOSS
# ==========================================
def focal_loss(gamma=2., alpha=0.25):
    def loss(y_true, y_pred):
        epsilon = 1e-7
        y_pred = K.clip(y_pred, epsilon, 1. - epsilon)
        pt = tf.where(K.equal(y_true, 1), y_pred, 1 - y_pred)
        return -K.mean(alpha * K.pow(1. - pt, gamma) * K.log(pt))
    return loss


# ==========================================
# 4. ADVANCED HYBRID MODEL
# ==========================================
def build_advanced_hybrid(input_shape):

    inputs = Input(shape=input_shape)

    # Multi-Scale CNN
    cnn1 = Conv1D(64, 3, padding='same', activation='relu')(inputs)
    cnn2 = Conv1D(64, 5, padding='same', activation='relu')(inputs)
    cnn3 = Conv1D(64, 7, padding='same', activation='relu')(inputs)

    cnn = Concatenate()([cnn1, cnn2, cnn3])  # 192 filters
    cnn = MaxPooling1D(2)(cnn)
    cnn = Dropout(0.3)(cnn)

    # Proper Residual connection
    res = Conv1D(192, 1, padding='same')(inputs)
    res = MaxPooling1D(2)(res)
    cnn = Add()([cnn, res])

    # BiLSTM
    lstm = Bidirectional(LSTM(64, return_sequences=True))(cnn)
    lstm = Dropout(0.3)(lstm)

    # Self Attention
    attention = MultiHeadAttention(num_heads=4, key_dim=32)(lstm, lstm)
    attention = Add()([attention, lstm])
    attention = LayerNormalization(epsilon=1e-6)(attention)

    # Global pooling
    x = GlobalAveragePooling1D()(attention)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.4)(x)

    outputs = Dense(1, activation='sigmoid')(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
        loss=focal_loss(),
        metrics=['accuracy']
    )

    return model


# ==========================================
# 5. CROSS PROJECT LOOP
# ==========================================
results = []

early_stopper = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

print("\nStarting Cross-Project Defect Prediction...\n")

for test_name in dataset_names:

    print("="*60)
    print(f"Testing on Target Project: {test_name}")
    print("="*60)

    # Train on remaining 4
    train_names = [n for n in dataset_names if n != test_name]
    df_train = pd.concat([datasets[n] for n in train_names], ignore_index=True)
    df_test = datasets[test_name]

    X_train = df_train.drop('class', axis=1).values
    y_train = df_train['class'].values
    X_test = df_test.drop('class', axis=1).values
    y_test = df_test['class'].values

    # Standardization
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    input_shape = (X_train.shape[1], 1)

    X_train = X_train.reshape((X_train.shape[0], input_shape[0], 1))
    X_test = X_test.reshape((X_test.shape[0], input_shape[0], 1))

    # Class weights
    weights = class_weight.compute_class_weight(
        'balanced',
        classes=np.unique(y_train),
        y=y_train
    )
    cw_dict = {0: weights[0], 1: weights[1]}

    # Build model
    model = build_advanced_hybrid(input_shape)

    # Train
    model.fit(
        X_train, y_train,
        epochs=25,
        batch_size=64,
        validation_split=0.1,
        class_weight=cw_dict,
        callbacks=[early_stopper],
        verbose=0
    )

    # Predict
    y_pred_prob = model.predict(X_test, verbose=0).ravel()

    # Find best threshold for F1
    best_f1 = 0
    best_threshold = 0.5

    for t in np.arange(0.1, 0.9, 0.01):
        preds = (y_pred_prob > t).astype(int)
        score = f1_score(y_test, preds, zero_division=0)
        if score > best_f1:
            best_f1 = score
            best_threshold = t

    # Final prediction using best threshold
    y_pred = (y_pred_prob > best_threshold).astype(int)

    print(f"Best threshold found: {best_threshold:.2f}")


    # Metrics
    fm = f1_score(y_test, y_pred, zero_division=0)
    mcc = matthews_corrcoef(y_test, y_pred)

    try:
        auc = roc_auc_score(y_test, y_pred_prob)
    except:
        auc = 0.5

    print(f"F1-score: {fm:.4f}")
    print(f"MCC     : {mcc:.4f}")
    print(f"AUC     : {auc:.4f}\n")

    results.append([test_name, fm, mcc, auc])


# ==========================================
# 6. FINAL TABLE
# ==========================================
results_df = pd.DataFrame(results, columns=['Test_Project', 'F1', 'MCC', 'AUC'])

print("\n" + "="*80)
print("FINAL CPDP RESULTS (Advanced Hybrid Model)")
print("="*80)
print(results_df)

results_df.to_csv("advanced_cpdp_results.csv", index=False)

print("\n✅ Done! Results saved as 'advanced_cpdp_results.csv'")